env:
  jest: true      # Разрешает глобальные функции Jest
  browser: true   # Если код будет работать в браузере
  es2021: true    # Использование ES2021
extends:
  - airbnb-base   # Базовые правила от Airbnb
parserOptions:
  ecmaVersion: latest  # Использование последней версии ECMAScript
  sourceType: module  # Использование модульной системы (import/export)
rules:
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]  # Разрешение на использование __filename и __dirname
  no-console: 0    # Разрешение на использование console (например, console.log)
  import/extensions: 
    - error
    - js: always   # Обязательные расширения для импортов в JS
plugins:
  - jest  # Подключаем плагин для Jest
